# Generated by Django 4.2 on 2023-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=128, verbose_name='Media title')),
                ('icon', models.CharField(max_length=128, verbose_name='Icon')),
                ('color', models.CharField(choices=[('primary', 'primary-color'), ('secondary', 'secondary-color'), ('accent', 'accent-color'), ('dark', 'dark-color')], max_length=128, verbose_name='Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='menubaseitems',
            options={'ordering': ('order',), 'verbose_name': 'Əsas menu linki', 'verbose_name_plural': 'Əsas menu linkləri'},
        ),
        migrations.AlterModelOptions(
            name='menusubitems',
            options={'ordering': ('order',), 'verbose_name': 'Köməkçi menu linki', 'verbose_name_plural': 'Köməkçi menu linkləri'},
        ),
    ]
