# Generated by Django 4.2 on 2023-05-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headerinfo_socialmediaicon_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderInfo',
            new_name='ContactInfo',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Əlaqə vasitələri', 'verbose_name_plural': 'Əlaqə vasitələri informasiya'},
        ),
        migrations.AlterModelOptions(
            name='socialmediaicon',
            options={'verbose_name': 'Sosial media', 'verbose_name_plural': 'Sosiallar'},
        ),
    ]
