# Generated by Django 4.2 on 2023-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_headerinfo_contactinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaicon',
            name='title',
        ),
        migrations.AddField(
            model_name='socialmediaicon',
            name='url',
            field=models.CharField(default='demo', max_length=128, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
