# Generated by Django 4.2 on 2023-05-03 06:11

import core.custom.custom_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_socialmediaicon_title_socialmediaicon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('pretitle', models.CharField(max_length=128, verbose_name='Ön başlıq')),
                ('title', models.CharField(max_length=128, verbose_name='Başlıq')),
                ('description', models.CharField(max_length=128, verbose_name='Açıqlama')),
                ('image', models.ImageField(upload_to=core.custom.custom_tools.get_carousel_image, verbose_name='Karusel şəkli')),
                ('left_button_text', models.CharField(max_length=128, verbose_name='Soldakı düymə mətni')),
                ('right_button_text', models.CharField(max_length=128, verbose_name='Sağdakı düymə mətni')),
            ],
            options={
                'verbose_name': 'Karusel',
                'verbose_name_plural': 'Karusel',
            },
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='color',
            field=models.CharField(choices=[('primary-color', 'primary'), ('secondary-color', 'secondary'), ('accent-color', 'accent'), ('dark-color', 'dark')], max_length=128, verbose_name='Color'),
        ),
    ]
