# Generated by Django 4.2 on 2023-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carousel_alter_socialmediaicon_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Açıqlama'),
        ),
    ]
