# Generated by Django 4.2 on 2023-05-03 12:48

import core.custom.custom_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carousel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=128, verbose_name='Ad')),
                ('image', models.ImageField(upload_to="/brand_images/", verbose_name='Brend şəkli')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlər',
            },
        ),
    ]
