# Generated by Django 4.2 on 2023-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.CharField(default='no-url/', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
