# Generated by Django 4.2 on 2023-05-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brand_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='left_button_url',
            field=models.CharField(default='no-url', max_length=128, verbose_name='Soldakı düymə url-i'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='right_button_url',
            field=models.CharField(default='no-url', max_length=128, verbose_name='Sağdakı düymə url-i'),
            preserve_default=False,
        ),
    ]
