# Generated by Django 4.2 on 2023-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carousel_left_button_url_carousel_right_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brand_image/', verbose_name='Brend şəkli'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='carousel_images/', verbose_name='Karusel şəkli'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='left_button_text',
            field=models.CharField(max_length=50, verbose_name='Soldakı düymə mətni'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='left_button_url',
            field=models.URLField(max_length=128, verbose_name='Soldakı düymə url-i'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='right_button_text',
            field=models.CharField(max_length=50, verbose_name='Sağdakı düymə mətni'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='right_button_url',
            field=models.URLField(max_length=128, verbose_name='Sağdakı düymə url-i'),
        ),
    ]
