# Generated by Django 4.2 on 2023-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_brand_image_alter_carousel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['sort_order'], 'verbose_name': 'Karusel', 'verbose_name_plural': 'Karusel'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
