# Generated by Django 4.2 on 2023-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carousel_options_carousel_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('pretitle', models.CharField(max_length=100, verbose_name='Ön başlıq')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('video_source', models.URLField(verbose_name='Video mənbə kodu')),
                ('image', models.ImageField(upload_to='video_section_image', verbose_name='Video cover')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('pretitle', models.CharField(max_length=100, verbose_name='Ön başlıq')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('button_text', models.CharField(max_length=100, verbose_name='Düymə mətni')),
                ('button_url', models.URLField(verbose_name='Düymə url-i')),
                ('image', models.ImageField(upload_to='welcome_section_images', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
