# Generated by Django 4.2 on 2023-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sectioninfo_image2_sectioninfo_secondary_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=128, verbose_name='Servis adı')),
                ('url', models.CharField(max_length=255, verbose_name='Servis URL-i')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='Servis ikon klası')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_images', verbose_name='Servis şəkli')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Servis açıqlaması')),
            ],
            options={
                'verbose_name': 'Servis ikonu',
                'verbose_name_plural': 'Servis ikonları',
            },
        ),
    ]
