# Generated by Django 4.2 on 2023-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_serviceicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceicon',
            name='type',
            field=models.CharField(choices=[('mini', 'Kiçik'), ('middle', 'Orta')], default='mini', max_length=64, verbose_name='Servis tipi'),
            preserve_default=False,
        ),
    ]
