# Generated by Django 4.2 on 2023-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_miniswipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniswipe',
            name='section_info',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='section_info',
        ),
        migrations.AlterField(
            model_name='miniswipe',
            name='idiom',
            field=models.TextField(verbose_name='Mətn'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.CharField(choices=[('welcome', 'Welcome section'), ('video', 'Video section'), ('service', 'Services section'), ('info', 'Info section'), ('testimonials', 'Testimonials section'), ('projects', 'Projects section')], max_length=255, verbose_name='Section seçin'),
        ),
    ]
