# Generated by Django 4.2 on 2023-05-15 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_brand_active_alter_carousel_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('title', models.CharField(max_length=255, verbose_name='Kateqorioya adı')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, max_length=150, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Mətn')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.category')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio proyektlər',
            },
        ),
        migrations.AlterField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='menubaseitems',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='menusubitems',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='miniswipe',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='miniswipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='miniswipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='url',
            field=models.URLField(max_length=255, verbose_name='Servis URL-i'),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivdirmi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images', verbose_name='Şəkil')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project', verbose_name='Proyekt')),
            ],
            options={
                'verbose_name': 'Portfolio şəkli',
                'verbose_name_plural': 'Portfolio şəkilləri',
            },
        ),
    ]
