# Generated by Django 4.2 on 2023-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_category_project_alter_brand_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('question', models.TextField(max_length=500, verbose_name='Sual')),
                ('answer', models.TextField(max_length=500, verbose_name='Cavab')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faq_images', verbose_name='Şəkil')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='InfoTag',
        ),
        migrations.AlterModelOptions(
            name='infotag',
            options={'ordering': ['sort_order'], 'verbose_name': 'İnfo Teq', 'verbose_name_plural': 'İnfo Teqlər'},
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.CharField(choices=[('welcome', 'Welcome section'), ('video', 'Video section'), ('service', 'Services section'), ('info', 'Info section'), ('testimonials', 'Testimonials section'), ('projects', 'Projects section'), ('what-we-can-do', 'What we can do section'), ('faq', 'FREQUENTLY ASKED')], max_length=255, verbose_name='Section seçin'),
        ),
    ]
