# Generated by Django 4.2 on 2023-05-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tag_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
