# Generated by Django 4.2 on 2023-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('title', models.CharField(max_length=255, verbose_name='Planın adı')),
                ('description', models.CharField(max_length=255, verbose_name='Planın açıqlaması')),
                ('price', models.CharField(max_length=255, verbose_name='Planın qiyməti')),
                ('currency', models.CharField(max_length=255, verbose_name='Plan qiymətinin valyutası')),
            ],
            options={
                'verbose_name': 'Servis paketi',
                'verbose_name_plural': 'Servis paketləri',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('fullname', models.CharField(max_length=255, verbose_name='Əməkdaşın ad, soyadı')),
                ('profession', models.CharField(max_length=255, verbose_name='Əməkdaşın vəzifəsi')),
                ('image', models.ImageField(upload_to='member_images', verbose_name='Əməkdaşın şəkli')),
                ('info', models.TextField(max_length=500, verbose_name='Əməkdaşın bio-su')),
                ('email', models.EmailField(max_length=100, verbose_name='Əməkdaşın elektron poçt ünvanı')),
            ],
            options={
                'verbose_name': 'Əməkdaş',
                'verbose_name_plural': 'Əməkdaşlar',
            },
        ),
    ]
