# Generated by Django 4.2 on 2023-05-18 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_serviceplan_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=150, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.CharField(choices=[('welcome', 'Welcome section'), ('video', 'Video section'), ('service', 'Services section'), ('info', 'Info section'), ('testimonials', 'Testimonials section'), ('projects', 'Projects section'), ('team', 'OUR TEAM')], max_length=255, verbose_name='Section seçin'),
        ),
    ]
