# Generated by Django 4.2 on 2023-05-18 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_teammember_slug_alter_sectioninfo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(default='Bakı şəh. Yasamal ray. Həsən bəy Zərdabi 2a', max_length=300, verbose_name='Ünvan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.CharField(choices=[('welcome', 'Welcome section'), ('video', 'Video section'), ('service', 'Services section'), ('info', 'Info section'), ('testimonials', 'Testimonials section'), ('projects', 'Projects section'), ('team', 'Our team section'), ('special_offer', ' Offer section')], max_length=255, verbose_name='Section seçin'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=150, verbose_name='Slug'),
        ),
    ]
