# Generated by Django 4.2 on 2023-05-18 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contactinfo_address_alter_sectioninfo_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
