# Generated by Django 4.2 on 2023-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='left_button_url',
            field=models.CharField(max_length=128, verbose_name='Soldakı düymə url-i'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='right_button_url',
            field=models.CharField(max_length=128, verbose_name='Sağdakı düymə url-i'),
        ),
        migrations.AlterField(
            model_name='infotag',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Düymə url-i'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='secondary_button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Əlavə düymə url-i'),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Servis URL-i'),
        ),
    ]
