# Generated by Django 4.2 on 2023-05-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_delete_carousel_delete_infotag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
