# Generated by Django 4.2 on 2023-05-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('pretitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='1-ci hissə ön başlıq')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='1-ci hissə başlıq')),
                ('description', models.TextField(blank=True, null=True, verbose_name='1-ci hissə açıqlama')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='1-ci hissə düymə mətni')),
                ('button_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='1-ci hissə düymə url-i')),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/contact_page', verbose_name='1-ci hissə şəkli')),
                ('pretitle_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2-ci hissə ön başlıq')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='2-ci hissə başlıq')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='core/contact_page', verbose_name='2-ci hissə şəkli ')),
            ],
            options={
                'verbose_name': 'Bizimlə əlaqə səhifəsi',
                'verbose_name_plural': 'Bizimlə əlaqə səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Təfsilatı')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='core.contactuspagedata')),
            ],
            options={
                'verbose_name': 'Akkordion',
                'verbose_name_plural': 'Akkordionlar',
            },
        ),
    ]
