# Generated by Django 4.2 on 2023-05-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_contactuspagedata_accordionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuspagedata',
            options={'verbose_name': 'Haqqımızda səhifəsi', 'verbose_name_plural': 'Haqqımızda səhifəsi'},
        ),
        migrations.RemoveField(
            model_name='contactuspagedata',
            name='image2',
        ),
        migrations.AlterField(
            model_name='contactuspagedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/ContactUsPageData/image', verbose_name='1-ci hissə şəkli'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/ProjectImage/image', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='core/TeamMember/image', verbose_name='Əməkdaşın şəkli'),
        ),
        migrations.CreateModel(
            name='AboutUsSwiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('image', models.ImageField(upload_to='core/AboutUsSwiper/image', verbose_name='Swiper şəkli')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipers', to='core.contactuspagedata')),
            ],
            options={
                'verbose_name': 'Akkordion',
                'verbose_name_plural': 'Akkordionlar',
            },
        ),
    ]
