# Generated by Django 4.2 on 2023-05-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubitems',
            name='base_header_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='home.menubaseitems', verbose_name='Parent header menu'),
        ),
    ]
