# Generated by Django 4.2 on 2023-05-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menuitems_remove_menusubitems_base_header_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='order',
        ),
    ]
