# Generated by Django 4.2 on 2023-05-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_menuitems_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('title', models.CharField(max_length=128, verbose_name='Ad')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('image', models.ImageField(upload_to='brand_image/', verbose_name='Brend şəkli')),
            ],
            options={
                'verbose_name': 'Brend',
                'verbose_name_plural': 'Brendlər',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'ordering': ['sort_order'], 'verbose_name': 'Header menu linki', 'verbose_name_plural': 'Header menu linkləri'},
        ),
    ]
