# Generated by Django 4.2 on 2023-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_brand_alter_menuitems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['sort_order'], 'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlər'},
        ),
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
