# Generated by Django 4.2 on 2023-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_brand_options_brand_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
