# Generated by Django 4.2 on 2023-05-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_brand_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-sort_order'], 'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlər'},
        ),
    ]
