# Generated by Django 4.2 on 2023-05-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_brand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='home/Brand/image', verbose_name='Brend şəkli'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='home/Carousel/image', verbose_name='Karusel şəkli'),
        ),
        migrations.AlterField(
            model_name='miniswipe',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/MiniSwipe/author_image', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/SectionInfo/image', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='home/SectionInfo/image_2', verbose_name='Əlavə şəkil '),
        ),
        migrations.AlterField(
            model_name='serviceicon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/ServiceIcon/image', verbose_name='Servis şəkli'),
        ),
    ]
