# Generated by Django 4.2 on 2023-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişdirilmə tarixi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivdirmi')),
                ('name', models.CharField(max_length=100, verbose_name='Ad və soyad')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(max_length=300, verbose_name='Mesaj mətni')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
