# Generated by Django 4.2 on 2023-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Is email sent?'),
        ),
    ]
