# Generated by Django 4.2 on 2023-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email_to',
            field=models.EmailField(default='', max_length=254, verbose_name='Email to'),
            preserve_default=False,
        ),
    ]
